name: diabetes-ml
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip=23.0.1
  - pip:
    - streamlit>=1.32.0
    - pandas==2.0.3
    - numpy==1.24.3
    - scikit-learn==1.3.0
    - matplotlib==3.7.2
    - scipy==1.10.1
    - xgboost==1.7.3
    - joblib==1.3.2
    - pickle5==0.0.12 